services:
  web:
    build: .    # dockerfile 위치
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app    # 현재 디렉토리를 컨테이너 내부의 /app에 연결
    ports:
      - "8000:8000"     # 호스트와 컨테이너 포트 연결
    env_file:
      - .env
    depends_on:
      - redis
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      # - "443:443"       # https를 열어줄 때만 사용하는 것
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # https 상태
      # - /etc/letsencrypt:/etc/letsencrypt
      # - /var/www/certbot:/var/www/certbot
    depends_on:
      - web

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data: